// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    district_health_summary: {
        name: "district_health_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DOUBLE */
          avg_health_insurance: number;
          /** @sqlType DOUBLE */
          avg_sanitation: number;
          /** @sqlType DOUBLE */
          avg_water_access: number;
          /** @sqlType DOUBLE */
          avg_female_literacy: number;
          /** @sqlType BIGINT */
          total_states: number;
          /** @sqlType BIGINT */
          total_districts: number;
        }>;
      };
    facilities_by_state: {
        name: "facilities_by_state";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    facility_stats: {
        name: "facility_stats";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          total_facilities: number;
          /** @sqlType BIGINT */
          states_covered: number;
          /** @sqlType BIGINT */
          cities_covered: number;
        }>;
      };
    health_indicators_by_state: {
        name: "health_indicators_by_state";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType DOUBLE */
          health_insurance_pct: number;
          /** @sqlType DOUBLE */
          sanitation_pct: number;
          /** @sqlType DOUBLE */
          water_access_pct: number;
          /** @sqlType DOUBLE */
          electricity_pct: number;
        }>;
      };
    hello_world: {
        name: "hello_world";
        parameters: {
          /** STRING - use sql.string() */
          message: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          value: string;
        }>;
      };
    mocked_sales: {
        name: "mocked_sales";
        parameters: {
          /** INT - use sql.int() */
          max_month_num: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType INT */
          month_num: number;
          /** @sqlType INT */
          revenue: number;
          /** @sqlType INT */
          expenses: number;
          /** @sqlType INT */
          customers: number;
        }>;
      };
  }
}
